"""Proof-of-sender checks for every route that has no logged-in user.

Every check here FAILS CLOSED: when the secret it needs is not configured the
route refuses the request (503) instead of trusting it, and any error while
checking counts as "not proven". A webhook that cannot prove who sent it can
create candidates, text and call real people, and rewrite screening results,
so "it was easier to leave it open" is never the right default.

Secrets (all set in Railway -> Variables, or backend/.env locally):

  TWILIO_AUTH_TOKEN          Twilio signs every webhook with it (X-Twilio-Signature).
  ELEVENLABS_TOOL_SECRET     You choose it. Sent by ElevenLabs as the X-CGR-Tool-Secret
                             header on the agent tools and the conversation-init
                             webhook (the app adds the header when it syncs them).
  ELEVENLABS_WEBHOOK_SECRET  Generated by ElevenLabs for the post-call webhook; the
                             request carries an ElevenLabs-Signature HMAC.
  SENDGRID_INBOUND_SECRET    You choose it. Put it in the Inbound Parse destination URL
                             as ?key=<secret> (or as the basic-auth password).
  JWT_SECRET                 Also signs the short-lived call-bridge stream URLs.

Local development without Twilio can set ALLOW_UNSIGNED_TWILIO_WEBHOOKS=true to
let unsigned Twilio callbacks through. Never set it on a live deployment.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import logging
import os
import time
from typing import Iterable, List, Optional

from fastapi import HTTPException, Request

logger = logging.getLogger("cgrecruit")

TOOL_SECRET_HEADER = "X-CGR-Tool-Secret"
ELEVENLABS_SIGNATURE_HEADER = "ElevenLabs-Signature"
# ElevenLabs signs with the send time; anything older than this is a replay.
ELEVENLABS_SIGNATURE_TOLERANCE_SECONDS = 30 * 60
# Twilio opens the media stream within seconds of fetching the TwiML.
STREAM_TOKEN_TTL_SECONDS = 5 * 60


def _env(name: str) -> str:
    return (os.getenv(name) or "").strip()


def _same(a: str, b: str) -> bool:
    return hmac.compare_digest((a or "").encode("utf-8"), (b or "").encode("utf-8"))


def _truthy(name: str) -> bool:
    return _env(name).lower() in ("1", "true", "yes", "on")


def _basic_auth_password(request: Request) -> str:
    auth = request.headers.get("authorization") or ""
    if not auth.lower().startswith("basic "):
        return ""
    try:
        decoded = base64.b64decode(auth.split(" ", 1)[1].strip()).decode("utf-8")
    except Exception:
        return ""
    return decoded.split(":", 1)[1] if ":" in decoded else ""


# ---------------------------------------------------------------------------
# Shared-secret webhooks
# ---------------------------------------------------------------------------

def require_shared_secret(
    request: Request,
    env_name: str,
    *,
    headers: Iterable[str] = ("x-webhook-secret",),
    query_param: Optional[str] = None,
    allow_basic_auth: bool = False,
    feature: str = "This webhook",
) -> None:
    """Raise unless the request presents the secret held in `env_name`.

    503 when the secret is not configured (the feature is off, never open),
    403 when it is missing or wrong. Constant-time comparison throughout."""
    secret = _env(env_name)
    if not secret:
        raise HTTPException(503, f"{feature} is disabled until {env_name} is set")
    presented = ""
    for name in headers:
        presented = request.headers.get(name) or ""
        if presented:
            break
    if not presented and query_param:
        presented = request.query_params.get(query_param) or ""
    if not presented and allow_basic_auth:
        presented = _basic_auth_password(request)
    if not presented or not _same(presented, secret):
        raise HTTPException(403, "Invalid webhook secret")


async def require_elevenlabs_tool_secret(request: Request) -> None:
    """FastAPI dependency for the voice agent's tool endpoints and the
    conversation-init webhook (they act on a phone number alone)."""
    require_shared_secret(
        request, "ELEVENLABS_TOOL_SECRET",
        headers=(TOOL_SECRET_HEADER,), feature="Voice-agent tools",
    )


def elevenlabs_tool_headers() -> dict:
    """Headers ElevenLabs must send on tool calls / the init webhook. Empty when
    the secret is unset (the endpoints then refuse every call)."""
    secret = _env("ELEVENLABS_TOOL_SECRET")
    return {TOOL_SECRET_HEADER: secret} if secret else {}


def require_sendgrid_inbound_secret(request: Request) -> None:
    require_shared_secret(
        request, "SENDGRID_INBOUND_SECRET",
        headers=("x-webhook-secret",), query_param="key", allow_basic_auth=True,
        feature="Inbound email",
    )


# ---------------------------------------------------------------------------
# ElevenLabs post-call HMAC
# ---------------------------------------------------------------------------

def elevenlabs_signature_valid(raw_body: bytes, header_value: str, secret: str,
                               now: Optional[float] = None) -> bool:
    """Check an `ElevenLabs-Signature: t=<unix>,v0=<hex hmac>` header.

    The signed payload is f"{t}.{raw body}", HMAC-SHA256 with the webhook
    secret. Stale timestamps are rejected so a captured request can't be
    replayed later."""
    if not (header_value and secret):
        return False
    parts = {}
    for chunk in header_value.split(","):
        if "=" in chunk:
            k, v = chunk.split("=", 1)
            parts.setdefault(k.strip(), []).append(v.strip())
    ts = (parts.get("t") or [""])[0]
    sigs = parts.get("v0") or []
    if not ts.isdigit() or not sigs:
        return False
    now = time.time() if now is None else now
    if abs(now - int(ts)) > ELEVENLABS_SIGNATURE_TOLERANCE_SECONDS:
        return False
    expected = hmac.new(
        secret.encode("utf-8"), ts.encode("utf-8") + b"." + (raw_body or b""), hashlib.sha256,
    ).hexdigest()
    return any(_same(expected, s) for s in sigs)


async def require_elevenlabs_signature(request: Request) -> bytes:
    """Verify the post-call webhook and return its raw body. Fails closed:
    without ELEVENLABS_WEBHOOK_SECRET the route is off and the 60-second
    transcript sweep (which reads calls back from the ElevenLabs API with your
    API key) records outbound calls instead."""
    secret = _env("ELEVENLABS_WEBHOOK_SECRET")
    if not secret:
        raise HTTPException(503, "Post-call webhook is disabled until ELEVENLABS_WEBHOOK_SECRET is set")
    raw = await request.body()
    header = request.headers.get(ELEVENLABS_SIGNATURE_HEADER) or ""
    if not elevenlabs_signature_valid(raw, header, secret):
        raise HTTPException(403, "Invalid signature")
    return raw


# ---------------------------------------------------------------------------
# Twilio request signatures
# ---------------------------------------------------------------------------

def _candidate_urls(request: Request) -> List[str]:
    """The URL Twilio signed, as each layer in front of us might report it.
    Twilio signs the exact URL it called, query string included."""
    path = request.url.path
    query = getattr(request.url, "query", "") or ""
    suffix = f"{path}?{query}" if query else path
    bases: List[str] = []
    explicit = _env("APP_PUBLIC_URL").rstrip("/")
    if explicit:
        bases.append(explicit)
    fwd_host = request.headers.get("x-forwarded-host") or request.headers.get("host") or ""
    fwd_proto = request.headers.get("x-forwarded-proto") or ""
    scheme = fwd_proto or request.url.scheme or "https"
    if fwd_host:
        bases.append(f"{scheme}://{fwd_host}")
        if scheme != "https":
            bases.append(f"https://{fwd_host}")
    netloc = getattr(request.url, "netloc", "")
    if netloc:
        bases.append(f"{request.url.scheme}://{netloc}")
    seen, out = set(), []
    for b in bases:
        url = b + suffix
        if url not in seen:
            seen.add(url)
            out.append(url)
    return out


async def twilio_request_is_authentic(request: Request) -> bool:
    """True only when the X-Twilio-Signature checks out against TWILIO_AUTH_TOKEN.

    No token configured -> False (unless ALLOW_UNSIGNED_TWILIO_WEBHOOKS=true
    for local development). Any error while checking -> False."""
    token = _env("TWILIO_AUTH_TOKEN")
    if not token:
        if _truthy("ALLOW_UNSIGNED_TWILIO_WEBHOOKS"):
            logger.warning("twilio webhook accepted UNSIGNED (ALLOW_UNSIGNED_TWILIO_WEBHOOKS is on)")
            return True
        logger.warning("twilio webhook refused: TWILIO_AUTH_TOKEN is not set")
        return False
    signature = request.headers.get("X-Twilio-Signature") or ""
    if not signature:
        return False
    try:
        from twilio.request_validator import RequestValidator

        validator = RequestValidator(token)
        method = (getattr(request, "method", "POST") or "POST").upper()
        params = {}
        if method == "POST":
            params = dict(await request.form())
        for url in _candidate_urls(request):
            if validator.validate(url, params, signature):
                return True
        return False
    except Exception as e:
        logger.warning("twilio signature check error (request refused): %s", e)
        return False


# ---------------------------------------------------------------------------
# Signed, expiring call-bridge stream URLs
# ---------------------------------------------------------------------------

def _stream_key() -> bytes:
    secret = _env("JWT_SECRET")
    if not secret:
        raise RuntimeError("JWT_SECRET is required")
    return hmac.new(secret.encode("utf-8"), b"cgr-twiml-stream-v1", hashlib.sha256).digest()


def sign_stream_token(conversation_id: str, ttl_seconds: int = STREAM_TOKEN_TTL_SECONDS,
                      now: Optional[float] = None) -> str:
    exp = int((time.time() if now is None else now) + ttl_seconds)
    mac = hmac.new(_stream_key(), f"{conversation_id}.{exp}".encode("utf-8"), hashlib.sha256).hexdigest()
    return f"{exp}.{mac}"


def stream_token_valid(conversation_id: str, token: str, now: Optional[float] = None) -> bool:
    try:
        exp_s, mac = (token or "").split(".", 1)
        exp = int(exp_s)
    except ValueError:
        return False
    if (time.time() if now is None else now) > exp:
        return False
    try:
        expected = hmac.new(_stream_key(), f"{conversation_id}.{exp}".encode("utf-8"), hashlib.sha256).hexdigest()
    except RuntimeError:
        return False
    return _same(expected, mac)
